# fly.toml app configuration file generated for phonebook-part3-fullstackopen-tam on 2024-05-23T14:33:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-part3-fullstackopen-tam'
primary_region = 'sin'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
